import uuid
from sqlalchemy import Column, Text, String, DateTime, ARRAY, ForeignKey, func
from sqlalchemy.dialects.postgresql import UUID
from app.database import Base


class AgentInsight(Base):
    """AgentInsight model - tracks proactive insights generated by the agent"""

    __tablename__ = "agent_insights"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    insight_type = Column(String(32), nullable=False)  # 'intention_loop' | 'arc' | 'tension'
    title = Column(Text, nullable=False)
    body = Column(Text, nullable=False)
    synthesis = Column(Text, nullable=False)  # full agent message shown in chat
    memory_ids = Column(ARRAY(UUID(as_uuid=True)), nullable=False)
    queued_at = Column(DateTime(timezone=True), server_default=func.now())
    sent_at = Column(DateTime(timezone=True), nullable=True)
    opened_at = Column(DateTime(timezone=True), nullable=True)
    dismissed_at = Column(DateTime(timezone=True), nullable=True)

    def __repr__(self):
        return f"<AgentInsight {self.id}>"
